swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Xenit System Information Module"
  contact:
    email: "engineering@xenit.eu"
basePath: "/alfresco/s/xenit/actuators/health"
tags:
  - name: "System"
    description: "System information API"
schemes:
  - "http"

##########################################################################
#                 PATHS                                                  #
##########################################################################
paths:
  "/":
    get:
      tags:
        - "Health"
      summary: "Retrieve health of the system"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "getHealthInfo"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HealthStatus"
        500:
          description: "Invalid status value"
          schema:
            $ref: "#/definitions/HealthStatus"
  "/details":
    get:
      tags:
        - "Health"
      summary: "Retrieve health information of the system"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "getHealthInfo"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/HealthInfo"
        500:
          description: "Failed to write Object"

##########################################################################
#                 DEFINITIONS                                            #
##########################################################################
definitions:

  # ROOT
  HealthStatus:
    type: object
    properties:
      status:
        $ref: '#/definitions/StatusEnum'
      message:
        type: string

  HealthInfo:
    type: object
    properties:
      name:
        type: string
      status:
        $ref: '#/definitions/StatusEnum'
      error:
        type: string
      details:
        type: object
        additionalProperties: { }
  # SYSTEM
  SystemInfo:
    type: object
    properties:
      os:
        $ref: '#/definitions/OperatingSystemInfo'
      java:
        $ref: '#/definitions/JavaInfo'
      cpu:
        $ref: '#/definitions/CpuInfo'
  OperatingSystemInfo:
    type: object
    properties:
      name:
        type: string
        example: "Linux"
      version:
        type: string
      arch:
        type: string
        example: "amd64"
  JavaInfo:
    type: object
    properties:
      input-arguments:
        type: array
        items:
          type: string
      garbage-collectors:
        type: array
        items:
          type: string
      system-properties:
        type: object
        additionalProperties:
          type: string
  CpuInfo:
    type: object
    properties:
      processors:
        type: integer
        format: int32
        example: 4
  ContentStoreInfo:
    type: object
    properties:
      access-time:
        type: integer
        format: int64
        example: 4
  # ALFRESCO
  AlfrescoInfo:
    type: object
    properties:
      id:
        type: string
      version:
        type: string
        example: "5.2.2 (r73ead3c7-b41)"
      war-manifest:
        type: object
        additionalProperties:
          type: string
      edition:
        type: string
        example: "Enterprise"
      modules:
        type: array
        items:
          $ref: '#/definitions/ModuleInfo'
      global-properties:
        type: object
        additionalProperties:
          type: string
  LicenseInfo:
    type: object
    properties:
      valid:
        type: boolean
      holder:
        type: string
      organisation:
        type: string
      remaining-days:
        type: integer
        format: int32
      max-users:
        type: integer
        format: int64
      clustering-enabled:
        type: boolean
      encryption-enabled:
        type: boolean
      heartbeat-disabled:
        type: boolean
  ModuleInfo:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      version:
        type: string
      install-state:
        type: string
  StatusInfo:
    type: object
    properties:
      readOnly:
        type: boolean
      auditEnabled:
        type: boolean
      thumbnailGeneration:
        type: boolean
  StatusEnum:
    type: string
    enum:
      - UP
      - DOWN