name: CI
on:
  push:
  workflow_dispatch:
env:
  GRADLE_OPTS: >-
    -Dorg.gradle.project.org.alfresco.maven.nexus.username=${{ secrets.ALFRESCO_NEXUS_USERNAME }}
    -Dorg.gradle.project.org.alfresco.maven.nexus.password=${{ secrets.ALFRESCO_NEXUS_PASSWORD }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavour: [ "community", "enterprise" ]
        version: [ "61", "62", "70", "71", "72", "73" ]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Set up JDK 11
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Login to Docker
        run: echo "${{ secrets.CLOUDSMITH_APIKEY }}" | docker login private.docker.xenit.eu --username "${{ secrets.CLOUDSMITH_USER }}" --password-stdin
      - name: Integration Test
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: :integration-tests:alfresco-${{ matrix.flavour }}-${{ matrix.version }}:integrationTest --parallel
      - name: 'Upload Test Reports'
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{ matrix.flavour }}-${{ matrix.version }}
          path: /home/runner/**/build/reports
          retention-days: 14
  publish:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: ${{  startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Set up JDK 11
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Add TAG_VERSION env property
        run: echo "TAG_VERSION=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.SONATYPE_S01_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.SONATYPE_S01_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
        run: ./gradlew publish --info


